// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eNUhYFuxeEr5zpXWZiRBEPoJs_ZTfMk',
    appId: '1:622089710662:web:93ae44b7b23cf85df42e47',
    messagingSenderId: '622089710662',
    projectId: 'doispedoisce',
    authDomain: 'doispedoisce.firebaseapp.com',
    storageBucket: 'doispedoisce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcsO3kyoYrtfwTkgMfy9nxpTFTYcW9Oug',
    appId: '1:622089710662:android:d72b644638c3a09bf42e47',
    messagingSenderId: '622089710662',
    projectId: 'doispedoisce',
    storageBucket: 'doispedoisce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7SB06q7j-8iJZySxYam4108KzI6oMR4',
    appId: '1:622089710662:ios:688bf29819d90964f42e47',
    messagingSenderId: '622089710662',
    projectId: 'doispedoisce',
    storageBucket: 'doispedoisce.appspot.com',
    iosClientId: '622089710662-hfop2mcjk43cesvmcrvgv2l7vof64jc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doispedoisce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX7SB06q7j-8iJZySxYam4108KzI6oMR4',
    appId: '1:622089710662:ios:688bf29819d90964f42e47',
    messagingSenderId: '622089710662',
    projectId: 'doispedoisce',
    storageBucket: 'doispedoisce.appspot.com',
    iosClientId: '622089710662-hfop2mcjk43cesvmcrvgv2l7vof64jc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.doispedoisce',
  );
}
